# -*- coding: utf-8 -*-
"""al1_sha256.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dEYspQeS8Pdf0IqKehpreNmwf53Ba8u8
"""

import hashlib
m=hashlib.sha256()
m.update(b"Hello")
m.update(b"World")
m.digest()