# -*- coding: utf-8 -*-
"""blake2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lnrAjB4iy6l5RgKi_dDt-Xyz2BEgyTLn
"""

from hashlib import blake2b
h=blake2b()
h.update(b'Hello World')
h.hexdigest()