# -*- coding: utf-8 -*-
"""hmac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SLcv6WXx6Et830pbp0HZpg0XiGGz-MEF
"""

import hmac,hashlib
m=hmac.new(b'secret key',digestmod=hashlib.blake2s)
m.update(b'message')
m.hexdigest()