# -*- coding: utf-8 -*-
"""md5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_oWUHSPAhZ5MPUmhL7sql2rTdVIbBGa
"""

import hashlib

def md5():
  a="Shamsiya"
  b=a.encode()
  c=hashlib.md5(b)
  hexa=c.hexdigest()
  print (hexa)
  return

md5()