# -*- coding: utf-8 -*-
"""salt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17mJTBfPpGHv1npShPrLkfmmeHj30CZFI
"""

import hashlib, uuid
def md5():
  a="Shamsiya"
  b=a.encode()
  c=hashlib.md5(b)
  hexa=c.hexdigest()
  print (hexa)
  password=hexa
  salt=uuid.uuid4().hex
  var=hashlib.sha512(salt+password)
for (i=0,i<=1000,i++)
{
    hashlib=sha512(hashlib);
}  
  return

md5()